version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_CHAT_API_URL=${VITE_CHAT_API_URL}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_APP_DESCRIPTION=${VITE_APP_DESCRIPTION}
      - VITE_ORGANIZATION_NAME=${VITE_ORGANIZATION_NAME}
      - VITE_ORGANIZATION_LOGO_URL=${VITE_ORGANIZATION_LOGO_URL}
      - VITE_ASSISTANT_NAME=${VITE_ASSISTANT_NAME}
      - VITE_MAX_CHAT_HISTORY=${VITE_MAX_CHAT_HISTORY}
      - VITE_PRIMARY_COLOR=${VITE_PRIMARY_COLOR}
      - VITE_SECONDARY_COLOR=${VITE_SECONDARY_COLOR}
      - VITE_ACCENT_COLOR=${VITE_ACCENT_COLOR}
      - VITE_ENABLE_REACTIONS=${VITE_ENABLE_REACTIONS}
      - VITE_ENABLE_MESSAGE_COPY=${VITE_ENABLE_MESSAGE_COPY}
      - VITE_ENABLE_FILE_UPLOAD=${VITE_ENABLE_FILE_UPLOAD}
      - VITE_ENABLE_AUDIO_UPLOAD=${VITE_ENABLE_AUDIO_UPLOAD}
      - VITE_MAX_FILE_SIZE=${VITE_MAX_FILE_SIZE}
      - VITE_ALLOWED_FILE_TYPES=${VITE_ALLOWED_FILE_TYPES}
      - VITE_ALLOWED_AUDIO_TYPES=${VITE_ALLOWED_AUDIO_TYPES}
      - VITE_MAX_AUDIO_DURATION=${VITE_MAX_AUDIO_DURATION}
      - VITE_DEV_MODE=${VITE_DEV_MODE}
    command: pnpm dev --host