FROM node:20-slim as builder

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente
COPY . .

# Argumentos de construcción para las variables de entorno
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_API_URL
ARG VITE_CHAT_API_URL
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_APP_NAME
ARG VITE_APP_DESCRIPTION
ARG VITE_ORGANIZATION_NAME
ARG VITE_ORGANIZATION_LOGO_URL
ARG VITE_ASSISTANT_NAME
ARG VITE_MAX_CHAT_HISTORY
ARG VITE_PRIMARY_COLOR
ARG VITE_SECONDARY_COLOR
ARG VITE_ACCENT_COLOR
ARG VITE_ENABLE_REACTIONS
ARG VITE_ENABLE_MESSAGE_COPY
ARG VITE_ENABLE_FILE_UPLOAD
ARG VITE_ENABLE_AUDIO_UPLOAD
ARG VITE_MAX_FILE_SIZE
ARG VITE_ALLOWED_FILE_TYPES
ARG VITE_ALLOWED_AUDIO_TYPES
ARG VITE_MAX_AUDIO_DURATION
ARG VITE_DEV_MODE

# Crear archivo .env en tiempo de build
RUN echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL\n\
VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY\n\
VITE_API_URL=$VITE_API_URL\n\
VITE_CHAT_API_URL=$VITE_CHAT_API_URL\n\
VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID\n\
VITE_APP_NAME=$VITE_APP_NAME\n\
VITE_APP_DESCRIPTION=$VITE_APP_DESCRIPTION\n\
VITE_ORGANIZATION_NAME=$VITE_ORGANIZATION_NAME\n\
VITE_ORGANIZATION_LOGO_URL=$VITE_ORGANIZATION_LOGO_URL\n\
VITE_ASSISTANT_NAME=$VITE_ASSISTANT_NAME\n\
VITE_MAX_CHAT_HISTORY=$VITE_MAX_CHAT_HISTORY\n\
VITE_PRIMARY_COLOR=$VITE_PRIMARY_COLOR\n\
VITE_SECONDARY_COLOR=$VITE_SECONDARY_COLOR\n\
VITE_ACCENT_COLOR=$VITE_ACCENT_COLOR\n\
VITE_ENABLE_REACTIONS=$VITE_ENABLE_REACTIONS\n\
VITE_ENABLE_MESSAGE_COPY=$VITE_ENABLE_MESSAGE_COPY\n\
VITE_ENABLE_FILE_UPLOAD=$VITE_ENABLE_FILE_UPLOAD\n\
VITE_ENABLE_AUDIO_UPLOAD=$VITE_ENABLE_AUDIO_UPLOAD\n\
VITE_MAX_FILE_SIZE=$VITE_MAX_FILE_SIZE\n\
VITE_ALLOWED_FILE_TYPES=$VITE_ALLOWED_FILE_TYPES\n\
VITE_ALLOWED_AUDIO_TYPES=$VITE_ALLOWED_AUDIO_TYPES\n\
VITE_MAX_AUDIO_DURATION=$VITE_MAX_AUDIO_DURATION\n\
VITE_DEV_MODE=$VITE_DEV_MODE" > .env

# Construir la aplicación
RUN npm run build

# Production stage
FROM nginx:alpine

# Copiar la configuración de nginx template
COPY nginx.conf /etc/nginx/templates/default.conf.template

# Copiar los archivos construidos
COPY --from=builder /app/dist /usr/share/nginx/html

# Variables que serán reemplazadas
ENV VITE_API_URL=${VITE_API_URL:-http://api:8000}

ENV VITE_CHAT_API_URL=${VITE_CHAT_API_URL:-http://api:8000}


# Comando para procesar el template y iniciar nginx
CMD ["/bin/sh", "-c", "envsubst '${VITE_API_URL} ${VITE_CHAT_API_URL}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]